# Generated by Django 6.0.4 on 2026-05-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='business_category',
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('Grocery / Supermarket', 'Grocery Market'), ('Electronics & Appliances', 'Electronic'), ('Clothing & Fashion', 'Fashion'), ('Pharmacy / Medical', 'Pharmacy'), ('Restaurant / Food', 'Food'), ('Hardware / Tools', 'Hardware'), ('Books / Stationery', 'Books'), ('Other', 'Other')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
