# Generated by Django 6.0.4 on 2026-05-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_store_business_category_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
