# Generated by Django 6.0.4 on 2026-05-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_store_gst_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=120)),
                ('product_code', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Tax', models.CharField(choices=[('0', "'0%' Exempt"), ('5', "'5%' GST"), ('12', "'12%' GST"), ('18', "'18%' GST"), ('28', "'28%' GST")], max_length=12)),
                ('opening_stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.CharField(choices=[('PCS', 'Pieces (Pcs)'), ('KG', 'Kilograms (Kg)'), ('L', 'Litres (L)'), ('Box', 'BOX'), ('Pack', 'Pack')], max_length=120)),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.store')),
            ],
        ),
    ]
