# Generated by Django 6.0.4 on 2026-05-11 07:29

from django.db import migrations

def create_categories(apps,schema_editor):
    Category=apps.get_model("App","Category")
    categories=[
        "Electronics",
        "Accessories",
        "Peripherals",
        "Storage",
        "Networking",
        "Other"
    ]

    for name in categories:
        Category.objects.get_or_create(
            name=name,
            is_default=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_category_product'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
