# Generated by Django 6.0.4 on 2026-05-13 05:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_add_default_product_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='App.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='App.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Bill_num', models.CharField(max_length=30, unique=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Credit', 'Credit')], max_length=30)),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.store')),
            ],
        ),
        migrations.CreateModel(
            name='Billitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.CharField(choices=[('0', "'0%' Exempt"), ('5', "'5%' GST"), ('12', "'12%' GST"), ('18', "'18%' GST"), ('28', "'28%' GST")], max_length=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('customer_type', models.CharField(choices=[('Individual', 'Individual'), ('Business / Firm', 'Business / Firm'), ('Wholesale', 'Wholsesale'), ('Retailer', 'Retailer')], max_length=120)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=120)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('gstin', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_term', models.CharField(choices=[('Immediate', 'Immediate'), ('Net 7 days', 'Net 7 days'), ('Net 15 days', 'Net 15 days'), ('Net 30 days', 'Net 30 days')], max_length=30)),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customers', to='App.store')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Bills', to='App.customer'),
        ),
    ]
