# Generated by Django 6.0.4 on 2026-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_product_categories_alter_product_store_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='Store',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Store',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Store',
            new_name='store',
        ),
        migrations.AlterField(
            model_name='product',
            name='Tax',
            field=models.CharField(choices=[('0', '0% Exempt'), ('5', '5% GST'), ('12', '12% GST'), ('18', '18% GST'), ('28', '28% GST')], default='18', max_length=12),
        ),
    ]
