# Generated by Django 6.0.4 on 2026-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_store_bill_store_rename_store_customer_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Tax',
            field=models.CharField(choices=[('0', '0% Exempt'), ('5', '5% GST'), ('12', '12% GST'), ('18', '18% GST'), ('28', '28% GST')], max_length=12),
        ),
    ]
