# Generated by Django 6.0.4 on 2026-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Tax',
            field=models.CharField(choices=[('0', '0% Exempt'), ('5', '5% GST'), ('12', '12% GST'), ('18', '18% GST'), ('28', '28% GST')], default='18', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
