# Generated by Django 6.0.4 on 2026-05-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_product_tax_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(choices=[('PCS', 'Pieces (Pcs)'), ('KG', 'Kilograms (Kg)'), ('L', 'Litres (L)'), ('Box', 'BOX'), ('Pack', 'Pack')], default='PCS', max_length=120),
        ),
    ]
