# Generated by Django 6.0.4 on 2026-05-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_product_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
    ]
