# Generated by Django 6.0.4 on 2026-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='tax',
            field=models.CharField(choices=[('0', '0% Exempt'), ('5', '5% GST'), ('12', '12% GST'), ('18', '18% GST'), ('28', '28% GST')], max_length=12),
        ),
    ]
