# Generated by Django 6.0.4 on 2026-05-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_product_current_stock_alter_billitem_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_stock',
        ),
    ]
