# Generated by Django 6.0.4 on 2026-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_product_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
