# Generated by Django 6.0.4 on 2026-05-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_billitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Finalized', 'Finalized'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
